/**
 * Drizzle ORM schema for the Momo application.
 * All tables are defined here and used for migration generation via drizzle-kit.
 *
 * Table overview:
 *  - users              Core user table, populated on first OAuth login
 *  - topics             User-defined project buckets to group tasks
 *  - tasks              All tasks (one-time, recurring, daily-eligible)
 *  - task_completions   Log of every task completion event
 *  - wishlist_items     Items a user wants to buy, with optional coin gating
 *  - achievements       Master list of available achievements (seeded)
 *  - user_achievements  Junction: which achievements a user has earned
 *  - api_keys           Personal Access Tokens for programmatic API access
 *  - linking_requests   Short-lived tokens for OAuth account linking flow
 *  - quest_postponements  Log of daily quest postponement events (for weekly review)
 *  - notification_channels  User-configured notification channels (ntfy, pushover, telegram, email; webhook future)
 *  - notification_log   Per-delivery log of every notification attempt (channel, status, error)
 *  - totp_backup_codes  One-time recovery codes for TOTP-based 2FA
 *  - authenticators     WebAuthn/Passkey credentials (passwordless login + 2FA)
 */

import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  date,
  time,
  decimal,
  jsonb,
  unique,
  uniqueIndex,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Enums ────────────────────────────────────────────────────────────────────

/** User interface theme preference */
export const themeEnum = pgEnum("theme", ["light", "dark", "system"]);

/** Task/topic priority levels */
export const priorityEnum = pgEnum("priority", ["HIGH", "NORMAL", "SOMEDAY"]);

/** Task type — controls recurrence and daily-quest eligibility */
export const taskTypeEnum = pgEnum("task_type", [
  "ONE_TIME",
  "RECURRING",
  "DAILY_ELIGIBLE",
]);

/** Task/user energy level — how much effort a task requires or the user has today */
export const energyLevelEnum = pgEnum("energy_level", ["HIGH", "MEDIUM", "LOW"]);

/** Wishlist item priority */
export const wishlistPriorityEnum = pgEnum("wishlist_priority", [
  "WANT",
  "NICE_TO_HAVE",
  "SOMEDAY",
]);

/** Wishlist item status */
export const wishlistStatusEnum = pgEnum("wishlist_status", [
  "OPEN",
  "BOUGHT",
  "DISCARDED",
]);

// ─── Tables ───────────────────────────────────────────────────────────────────

/**
 * Core user table.
 * Populated/updated on first OAuth login via Auth.js Drizzle adapter.
 * Extended with Momo-specific gamification and preference fields.
 *
 * The columns `name`, `email`, `emailVerified`, and `image` are required by
 * the Auth.js Drizzle adapter. Custom Momo fields are added alongside them.
 */
export const users = pgTable("users", {
  /** Primary key — UUID generated by the DB */
  id: uuid("id").primaryKey().defaultRandom(),

  /** Display name from the OAuth provider (required by Auth.js adapter) */
  name: text("name"),

  /** Email from the OAuth provider (required by Auth.js adapter) */
  email: text("email").unique(),

  /** Timestamp of email verification (required by Auth.js adapter) */
  emailVerified: timestamp("email_verified", { mode: "date" }),

  /** Avatar URL from the OAuth provider (required by Auth.js adapter) */
  image: text("image"),

  /** Composite identifier from the OAuth provider (e.g. "github:12345678") */
  providerId: text("provider_id").unique(),

  /** Gamification coin balance */
  coins: integer("coins").notNull().default(0),

  /** Gamification level */
  level: integer("level").notNull().default(1),

  /** Current streak length in days */
  streakCurrent: integer("streak_current").notNull().default(0),

  /** All-time maximum streak length */
  streakMax: integer("streak_max").notNull().default(0),

  /** Date of the last streak-qualifying action */
  streakLastDate: date("streak_last_date"),

  /** Month (YYYY-MM) when the streak shield was last consumed. NULL = available. */
  streakShieldUsedMonth: text("streak_shield_used_month"),

  /** Monthly budget for wishlist tracking (decimal for currency precision) */
  monthlyBudget: decimal("monthly_budget", { precision: 10, scale: 2 }),

  /** Whether the user has enabled push notifications */
  notificationEnabled: boolean("notification_enabled").notNull().default(false),

  /** Time of day for the daily notification (24h format, in the user's local timezone) */
  notificationTime: time("notification_time").notNull().default("08:00"),

  /**
   * IANA timezone identifier (e.g. "Europe/Berlin", "America/New_York").
   * Used to interpret notificationTime in the user's local time rather than UTC.
   * NULL falls back to UTC.
   */
  timezone: text("timezone"),

  /**
   * Opt-in flag for the "Due today" reminder (see sendDueTodayNotifications in lib/push.ts).
   * When true, the cron dispatcher sends a notification at the user's
   * configured notificationTime *if* there is at least one non-completed,
   * non-snoozed task whose due_date (or next_due_date, for recurring tasks)
   * is today in the user's timezone. Silent on empty — no "all clear" pings.
   * Default false so existing users don't get new noise without consent.
   */
  dueTodayReminderEnabled: boolean("due_today_reminder_enabled")
    .notNull()
    .default(false),

  /**
   * Opt-in flag for per-task recurring due reminders (see sendRecurringDueNotifications in lib/push.ts).
   * When true, the cron dispatcher sends an individual notification for each
   * recurring task whose next_due_date is today in the user's timezone.
   * Suppressed when morningBriefingEnabled is true (briefing already covers due tasks).
   * Default false so existing users don't get new noise without consent.
   */
  recurringDueReminderEnabled: boolean("recurring_due_reminder_enabled")
    .notNull()
    .default(false),

  /**
   * Opt-in daily digest: consolidates quest + due tasks + streak + achievements
   * into one push at `morningBriefingTime`. Replaces individual quest and
   * due-today reminders when enabled.
   */
  morningBriefingEnabled: boolean("morning_briefing_enabled")
    .notNull()
    .default(false),

  /**
   * Time of day for the morning briefing (24h format, user's local timezone).
   * Separate from notificationTime so users can get the digest earlier/later
   * than individual reminders. Default: 08:00.
   */
  morningBriefingTime: time("morning_briefing_time").notNull().default("08:00"),

  /** User's preferred colour theme */
  theme: themeEnum("theme").notNull().default("system"),

  /** How many times the user has postponed their daily quest today */
  questPostponesToday: integer("quest_postpones_today").notNull().default(0),

  /** Date on which questPostponesToday was last incremented — used for daily reset */
  questPostponedDate: date("quest_postponed_date"),

  /** Maximum number of daily quest postponements allowed per day (1–5, default 3) */
  questPostponeLimit: integer("quest_postpone_limit").notNull().default(3),

  /**
   * Cumulative count of tasks ever created by this user.
   * Incremented on createTask() and never decremented — gives a true "tasks created" stat
   * even after tasks are deleted.
   */
  totalTasksCreated: integer("total_tasks_created").notNull().default(0),

  /** Whether to show an affirmation/quote after completing the daily quest (default: on) */
  emotionalClosureEnabled: boolean("emotional_closure_enabled").notNull().default(true),

  /** Today's self-reported energy level for daily quest matching. Null = not yet checked in today. */
  energyLevel: energyLevelEnum("energy_level"),

  /** Date on which energyLevel was set (YYYY-MM-DD in user's timezone) — used for daily reset */
  energyLevelDate: date("energy_level_date"),

  /**
   * TOTP secret for two-factor authentication, encrypted at rest with
   * AES-256-GCM (see lib/utils/crypto.ts and TOTP_ENCRYPTION_KEY env var).
   * NULL when 2FA is not configured. The plaintext secret is never stored.
   */
  totpSecret: text("totp_secret"),

  /**
   * Timestamp when the user successfully verified their TOTP setup with
   * the first valid code. While NULL, 2FA is treated as inactive even if
   * totpSecret is set (defensive — should not occur in practice because
   * setup is committed atomically). Acts as the source of truth for
   * "is 2FA enabled for this user".
   */
  totpEnabledAt: timestamp("totp_enabled_at", { withTimezone: true }),

  /**
   * SHA-256 hash of the user's personal iCal calendar feed token.
   * NULL = no feed active. When set, the plaintext token forms the URL
   * `/api/calendar/<token>.ics` that third-party calendar clients
   * (Google/Apple/Outlook) subscribe to. Exactly one active token per user;
   * regenerating replaces the hash and immediately invalidates the old URL.
   * Unique to enforce O(1) lookup during feed requests.
   */
  calendarFeedTokenHash: text("calendar_feed_token_hash").unique(),

  /** Timestamp when the current calendar feed token was generated — shown in the settings UI */
  calendarFeedTokenCreatedAt: timestamp("calendar_feed_token_created_at", {
    withTimezone: true,
  }),

  /** Whether the user has completed the onboarding wizard. False for new users. */
  onboardingCompleted: boolean("onboarding_completed").notNull().default(false),

  /**
   * End date of vacation mode (YYYY-MM-DD, inclusive). Null = no active vacation.
   * When set, all RECURRING tasks have their pausedAt/pausedUntil columns populated.
   * A daily cron job auto-ends vacation once this date has passed.
   */
  vacationEndDate: date("vacation_end_date"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Auth.js required tables for the Drizzle adapter.
 * These must match the exact column structure expected by @auth/drizzle-adapter.
 * See: https://authjs.dev/getting-started/adapters/drizzle
 */

/** OAuth account links — one user can have multiple OAuth accounts */
export const accounts = pgTable(
  "accounts",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (table) => ({
    compoundKey: unique().on(table.provider, table.providerAccountId),
  })
);

/** Active sessions — sessionToken is the primary key */
export const sessions = pgTable("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),

  /**
   * Timestamp at which the second factor (TOTP / backup code / passkey) was
   * verified for this specific session. NULL means the user is logged in
   * via OAuth but has not yet completed the second-factor challenge —
   * protected routes must redirect to /login/2fa in that case. Reset to
   * NULL on every new session. A session created by a passwordless passkey
   * login is treated as inherently second-factor-satisfied and is written
   * with this column already set.
   *
   * Historically named `totp_verified_at` (legacy drizzle field
   * `totpVerifiedAt`). Renamed when Passkeys were added. The on-disk column
   * is now `second_factor_verified_at`.
   */
  secondFactorVerifiedAt: timestamp("second_factor_verified_at", {
    withTimezone: true,
  }),

  /** When this session was created (NULL for legacy sessions) */
  createdAt: timestamp("created_at", { withTimezone: true }),

  /** Last time metadata was refreshed (throttled to ~1h intervals) */
  lastActiveAt: timestamp("last_active_at", { withTimezone: true }),

  /** Raw User-Agent header captured on login / first request */
  userAgent: text("user_agent"),

  /** Client IP (from x-forwarded-for / x-real-ip / direct) */
  ipAddress: text("ip_address"),
});

/** Magic link / email verification tokens */
export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (table) => ({
    compositeKey: unique().on(table.identifier, table.token),
  })
);

/**
 * Topics — user-defined project buckets to group tasks.
 * Examples: "Moving", "Tax Return", "Health", "Side Project"
 */
export const topics = pgTable("topics", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  title: text("title").notNull(),

  description: text("description"),

  /** Optional hex or CSS color for UI display */
  color: text("color"),

  /** Optional emoji or icon identifier */
  icon: text("icon"),

  /** Priority affects daily quest topic selection */
  priority: priorityEnum("priority").notNull().default("NORMAL"),

  /** Archived topics are hidden from the main view but not deleted */
  archived: boolean("archived").notNull().default(false),

  /**
   * Sequential topics enforce implicit ordering: only the first still-open task
   * (lowest sort_order, not snoozed) is eligible for daily quest selection.
   * Later tasks are blocked until earlier ones are completed. Opt-in per topic.
   */
  sequential: boolean("sequential").notNull().default(false),

  /**
   * Default energy level inherited by new tasks created in this topic.
   * Useful for "Sport" (HIGH) or "E-Mails beantworten" (LOW) topics — saves
   * the user from picking the level on every task. NULL = no default.
   * Existing tasks are not retro-tagged when this changes.
   */
  defaultEnergyLevel: energyLevelEnum("default_energy_level"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Tasks — the core entity of Momo.
 * Supports one-time, recurring, and daily-quest-eligible types.
 */
export const tasks = pgTable("tasks", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** Optional topic association */
  topicId: uuid("topic_id").references(() => topics.id, {
    onDelete: "set null",
  }),

  title: text("title").notNull(),

  notes: text("notes"),

  /**
   * Task type:
   *  - ONE_TIME: completed once and done
   *  - RECURRING: repeats on a schedule (recurrence_interval days)
   *  - DAILY_ELIGIBLE: can be selected as the daily quest
   */
  type: taskTypeEnum("type").notNull(),

  priority: priorityEnum("priority").notNull().default("NORMAL"),

  /** For RECURRING tasks: number of days between occurrences */
  recurrenceInterval: integer("recurrence_interval"),

  /** Original due date (user-set) */
  dueDate: date("due_date"),

  /** Computed next due date for recurring tasks */
  nextDueDate: date("next_due_date"),

  /** Set when a ONE_TIME task is completed */
  completedAt: timestamp("completed_at"),

  /** Coin reward for completing this task */
  coinValue: integer("coin_value").notNull().default(1),

  /** Whether this task is currently selected as the daily quest */
  isDailyQuest: boolean("is_daily_quest").notNull().default(false),

  /** Date on which this task was last assigned as the daily quest (YYYY-MM-DD in user's timezone) */
  dailyQuestDate: date("daily_quest_date"),

  /** How many times this task has been postponed as a daily quest (across all days) */
  postponeCount: integer("postpone_count").notNull().default(0),

  /** Estimated time to complete this task in minutes (5 / 15 / 30 / 60 / null = unknown) */
  estimatedMinutes: integer("estimated_minutes"),

  /** Date until which this task is snoozed/hidden (YYYY-MM-DD). Null = active/visible. */
  snoozedUntil: date("snoozed_until"),

  /** Energy level required to complete this task. Null = matches any energy state. */
  energyLevel: energyLevelEnum("energy_level"),

  /** Sort position within a topic. Lower values appear first. Default 0, assigned sequentially on creation. */
  sortOrder: integer("sort_order").notNull().default(0),

  /**
   * Date when this task was paused (YYYY-MM-DD). Null = not paused.
   * Set by vacation mode activation; used to calculate the actual pause
   * duration when unpausing (nextDueDate shifts by `today - pausedAt` days).
   */
  pausedAt: date("paused_at"),

  /**
   * Date until which this task is paused (YYYY-MM-DD, inclusive). Null = active.
   * Paused tasks are excluded from daily quest selection, due-today notifications,
   * and the iCal feed. Distinct from snoozedUntil: pause also shifts nextDueDate
   * on deactivation and excludes the period from habit streak calculations.
   */
  pausedUntil: date("paused_until"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Task completions log.
 * Every completion event is recorded here — including recurring task completions.
 */
export const taskCompletions = pgTable("task_completions", {
  id: uuid("id").primaryKey().defaultRandom(),

  taskId: uuid("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  completedAt: timestamp("completed_at").notNull().defaultNow(),
});

/**
 * Energy check-in history.
 * Every energy check-in writes a row here — multiple entries per user per day
 * are explicitly allowed because users may re-check-in (morning HIGH, afternoon
 * LOW). The "current" value is the row with the largest createdAt for today.
 *
 * The cached current value is also stored on `users.energyLevel` /
 * `users.energyLevelDate` for fast dashboard reads — this table is for the
 * historical Stats view and pattern analysis.
 */
export const energyCheckins = pgTable(
  "energy_checkins",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    /**
     * Local date (YYYY-MM-DD) in the user's timezone at the moment of
     * check-in. Stored as the user's local day, not UTC, so calendar-day
     * grouping in the Stats view does the right thing for users east of UTC.
     */
    date: date("date").notNull(),

    /** The reported energy level. */
    energyLevel: energyLevelEnum("energy_level").notNull(),

    /** Wall-clock UTC timestamp — used for time-of-day analyses later. */
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    /** Per-user-per-day index — supports the "what is today's level" lookup. */
    userDateIdx: index("energy_checkins_user_date_idx").on(table.userId, table.date),
  })
);

/**
 * Wishlist items — things the user wants to buy.
 * Optionally gated behind a coin threshold for mindful spending.
 */
export const wishlistItems = pgTable("wishlist_items", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  title: text("title").notNull(),

  /** Price in the user's currency (stored as decimal for precision) */
  price: decimal("price", { precision: 10, scale: 2 }),

  /** Optional product/service URL */
  url: text("url"),

  priority: wishlistPriorityEnum("priority").notNull(),

  status: wishlistStatusEnum("status").notNull().default("OPEN"),

  /** Minimum coin balance required to mark as bought */
  coinUnlockThreshold: integer("coin_unlock_threshold"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Master achievements table.
 * Seeded with all available achievements; users earn them via user_achievements.
 */
export const achievements = pgTable("achievements", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** Unique machine-readable key (e.g. "first_task_completed") */
  key: text("key").notNull().unique(),

  title: text("title").notNull(),

  description: text("description").notNull(),

  /** Emoji or icon identifier for display */
  icon: text("icon").notNull(),
});

/**
 * Junction table tracking which achievements each user has earned.
 * The unique index on (user_id, achievement_id) prevents duplicate awards.
 */
export const userAchievements = pgTable(
  "user_achievements",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    achievementId: uuid("achievement_id")
      .notNull()
      .references(() => achievements.id, { onDelete: "cascade" }),

    earnedAt: timestamp("earned_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("user_achievements_user_id_achievement_id_unique").on(
      table.userId,
      table.achievementId
    ),
  ]
);

/**
 * Personal Access Tokens (API Keys) for programmatic access to the Momo API.
 *
 * Each key is stored as a SHA-256 hash of the plaintext token — the plaintext
 * is only ever shown once at creation time and never persisted.
 *
 * Key format (256-bit entropy): `momo_live_<44 chars base64url(32 random bytes)>`
 *
 * Fields:
 *  - keyHash    SHA-256(plaintext key) — used for O(1) lookup at auth time
 *  - keyPrefix  First 16 chars of the plaintext + "..." for display in the UI
 *  - readonly   If true, the key may only be used for GET requests
 *  - expiresAt  NULL = never expires; otherwise refused after this timestamp
 *  - revokedAt  NULL = active; set to revoke the key immediately
 *  - lastUsedAt Updated on each successful auth — useful for activity tracking
 */
export const apiKeys = pgTable("api_keys", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** User-defined label (e.g. "Claude MCP", "Home automation") */
  name: text("name").notNull(),

  /** SHA-256 hash of the plaintext API key — indexed, O(1) lookup */
  keyHash: text("key_hash").notNull().unique(),

  /** Display prefix: first 16 chars of plaintext + "..." (never the full key) */
  keyPrefix: text("key_prefix").notNull(),

  /** If true, key may only be used for GET requests (read-only access) */
  readonly: boolean("readonly").notNull().default(false),

  /** NULL = never expires */
  expiresAt: timestamp("expires_at"),

  /** Timestamp of last successful authentication — NULL if never used */
  lastUsedAt: timestamp("last_used_at"),

  /** Set when the key is revoked — NULL means the key is still active */
  revokedAt: timestamp("revoked_at"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Short-lived tokens used during the OAuth account linking flow.
 *
 * When a logged-in user wants to connect an additional OAuth provider, Momo:
 *  1. Creates a linking_request record with the user's ID and target provider
 *  2. Redirects the user through the OAuth flow
 *  3. In the OAuth callback, reads this token to find the original user and
 *     merge the new OAuth account onto them
 *
 * Tokens expire after 5 minutes to limit the attack surface.
 */
export const linkingRequests = pgTable("linking_requests", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user who initiated the linking request */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** Target OAuth provider (e.g. "github", "discord", "google", "keycloak") */
  provider: text("provider").notNull(),

  /** Tokens expire after 5 minutes */
  expiresAt: timestamp("expires_at").notNull(),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Cron run log — one row per cron job execution.
 * Used to track push-notification delivery history and detect stale/missing cron jobs.
 * Visible on the admin page and via /api/health (non-blocking).
 */
export const cronRuns = pgTable("cron_runs", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** Cron job name (e.g. "daily-quest") */
  name: text("name").notNull(),

  /** When the cron started */
  ranAt: timestamp("ran_at", { withTimezone: true }).notNull().defaultNow(),

  /** Number of push notifications successfully sent */
  sent: integer("sent").notNull().default(0),

  /** Number of push notifications that failed */
  failed: integer("failed").notNull().default(0),

  /** Execution time in milliseconds */
  durationMs: integer("duration_ms"),
});

/**
 * Per-device push subscriptions.
 *
 * One row per (user, browser/device) combination. The push endpoint URL is
 * globally unique — it identifies a specific browser push subscription.
 * This allows a user to receive notifications on multiple devices simultaneously.
 *
 * Lifecycle:
 *  - Created/updated when user enables notifications on a device (POST /api/push/subscribe)
 *  - Deleted when user disables notifications on that device (DELETE /api/push/subscribe)
 *  - Automatically deleted by sendPushNotification() when the push service returns 410 Gone
 */
export const pushSubscriptions = pgTable("push_subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user this subscription belongs to */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /**
   * The push endpoint URL — globally unique, identifies one browser/device.
   * Used as the upsert key: subscribing twice from the same device updates the row.
   */
  endpoint: text("endpoint").notNull().unique(),

  /** Full W3C PushSubscription JSON (endpoint + keys) */
  subscription: jsonb("subscription").notNull(),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Quest postponement log — one row per daily quest postponement.
 * Used to compute precise weekly postponement counts for the weekly review feature.
 * Historical data starts accumulating from the migration date forward.
 */
export const questPostponements = pgTable("quest_postponements", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user who postponed the quest */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** The task that was postponed */
  taskId: uuid("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),

  /** When the postponement happened */
  postponedAt: timestamp("postponed_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * User-configured notification channels (ntfy.sh, Pushover, Telegram, etc.).
 *
 * Each user may have at most one channel per type. The channel-specific
 * configuration is stored as JSONB — adding new channel types requires no
 * schema migration.
 *
 * Config shapes:
 *  - ntfy:     { topic: string, server?: string }
 *  - pushover: { userKey: string, appToken: string }
 *  - telegram: { botToken: string, chatId: string }
 *  - email:    { address: string }                     (SMTP creds via env vars)
 *  - webhook:  { url: string, secret?: string }        (future)
 */
export const notificationChannels = pgTable(
  "notification_channels",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /** The user who configured this channel */
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    /** Channel type identifier (e.g. "ntfy", "pushover", "telegram") */
    type: text("type").notNull(),

    /** Channel-specific configuration as JSONB */
    config: jsonb("config").notNull(),

    /** Whether this channel is currently active */
    enabled: boolean("enabled").notNull().default(true),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    unique("notification_channels_user_id_type_unique").on(table.userId, table.type),
  ]
);

/**
 * Per-delivery log of every notification attempt.
 *
 * Each row represents a single send attempt to one channel for one user.
 * Used by the Settings → Notification History section so users can debug
 * delivery issues ("did ntfy actually fire?"). Rows older than 30 days are
 * pruned by the `notification-log-cleanup` cron job.
 */
export const notificationLog = pgTable(
  "notification_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /** The user who received (or should have received) this notification */
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    /** Delivery channel: "web-push", "ntfy", "pushover", "telegram", "email" */
    channel: text("channel").notNull(),

    /** Notification title (short summary shown to the user) */
    title: text("title").notNull(),

    /** Notification body text (may be null for minimal payloads) */
    body: text("body"),

    /** Delivery outcome: "sent" or "failed" */
    status: text("status").notNull(),

    /** Error message when status is "failed"; null on success */
    error: text("error"),

    sentAt: timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_notification_log_user_sent").on(table.userId, table.sentAt),
  ]
);

/**
 * One-time backup codes for TOTP recovery.
 * Each row stores the SHA-256 hash of a single 10-character alphanumeric
 * code (mirrors the api_keys hashing pattern). Codes are generated in
 * batches of 10 during setup or regeneration; the plaintext is shown to
 * the user exactly once. `usedAt` flips a code to consumed — codes are
 * single-use to prevent replay.
 */
export const totpBackupCodes = pgTable("totp_backup_codes", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** SHA-256 hex digest of the plaintext code */
  codeHash: text("code_hash").notNull(),

  /** Set when the code is consumed; NULL means the code is still valid */
  usedAt: timestamp("used_at", { withTimezone: true }),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * WebAuthn / Passkey credentials.
 *
 * Follows the Auth.js authenticators schema but is managed directly by the
 * Momo webauthn module (`lib/webauthn.ts`) — we do not use the Auth.js
 * Passkey provider because it requires `session: "jwt"` and Momo uses
 * database sessions. Instead, the custom endpoints under
 * `app/api/auth/passkey/*` drive registration, login, and second-factor
 * assertions using `@simplewebauthn/server`.
 *
 * One user can have multiple passkeys (e.g. iPhone Touch ID, Windows Hello,
 * hardware key). Deleting a user cascades to all of their passkeys. Deleting
 * a single passkey revokes it — authentication attempts with that credential
 * ID will fail afterwards.
 *
 * Presence of a row in this table counts as a registered second factor for
 * the purposes of `userHasSecondFactor()` in `lib/totp.ts`.
 */
export const authenticators = pgTable(
  "authenticators",
  {
    /** Credential ID issued by the authenticator (base64url of raw bytes). */
    credentialID: text("credential_id").notNull().unique(),

    /** Owning user — cascades on delete. */
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    /**
     * Mirrors the Auth.js adapter column. We set this to the same value as
     * credentialID because Momo does not use the Auth.js Passkey provider,
     * but the column is kept for adapter compatibility and potential future
     * migration.
     */
    providerAccountId: text("provider_account_id").notNull(),

    /** COSE public key (base64url). */
    credentialPublicKey: text("credential_public_key").notNull(),

    /** Signature counter — incremented on every successful assertion. */
    counter: integer("counter").notNull(),

    /** "singleDevice" | "multiDevice" (synced passkey). */
    credentialDeviceType: text("credential_device_type").notNull(),

    /** Whether the credential is backed up to a cloud keychain. */
    credentialBackedUp: boolean("credential_backed_up").notNull(),

    /**
     * Comma-separated list of AuthenticatorTransport values
     * (e.g. "internal,hybrid"). Used to hint the browser during assertion.
     */
    transports: text("transports"),

    /**
     * User-provided display name ("iPhone", "YubiKey 5C"). Editable from
     * the settings page. NULL when the user skipped the name prompt.
     */
    name: text("name"),

    /** When this credential was registered. */
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    /** Last time this credential was used for an assertion. */
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  },
  (table) => ({
    compositePk: primaryKey({
      columns: [table.userId, table.credentialID],
    }),
  })
);

// ─── Relations ────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  accounts: many(accounts),
  sessions: many(sessions),
  topics: many(topics),
  tasks: many(tasks),
  taskCompletions: many(taskCompletions),
  wishlistItems: many(wishlistItems),
  userAchievements: many(userAchievements),
  apiKeys: many(apiKeys),
  linkingRequests: many(linkingRequests),
  pushSubscriptions: many(pushSubscriptions),
  questPostponements: many(questPostponements),
  notificationChannels: many(notificationChannels),
  notificationLog: many(notificationLog),
  totpBackupCodes: many(totpBackupCodes),
  authenticators: many(authenticators),
}));

export const apiKeysRelations = relations(apiKeys, ({ one }) => ({
  user: one(users, { fields: [apiKeys.userId], references: [users.id] }),
}));

export const linkingRequestsRelations = relations(linkingRequests, ({ one }) => ({
  user: one(users, { fields: [linkingRequests.userId], references: [users.id] }),
}));

export const topicsRelations = relations(topics, ({ one, many }) => ({
  user: one(users, { fields: [topics.userId], references: [users.id] }),
  tasks: many(tasks),
}));

export const tasksRelations = relations(tasks, ({ one, many }) => ({
  user: one(users, { fields: [tasks.userId], references: [users.id] }),
  topic: one(topics, { fields: [tasks.topicId], references: [topics.id] }),
  completions: many(taskCompletions),
}));

export const taskCompletionsRelations = relations(
  taskCompletions,
  ({ one }) => ({
    task: one(tasks, {
      fields: [taskCompletions.taskId],
      references: [tasks.id],
    }),
    user: one(users, {
      fields: [taskCompletions.userId],
      references: [users.id],
    }),
  })
);

export const wishlistItemsRelations = relations(wishlistItems, ({ one }) => ({
  user: one(users, { fields: [wishlistItems.userId], references: [users.id] }),
}));

export const userAchievementsRelations = relations(
  userAchievements,
  ({ one }) => ({
    user: one(users, {
      fields: [userAchievements.userId],
      references: [users.id],
    }),
    achievement: one(achievements, {
      fields: [userAchievements.achievementId],
      references: [achievements.id],
    }),
  })
);

export const pushSubscriptionsRelations = relations(pushSubscriptions, ({ one }) => ({
  user: one(users, { fields: [pushSubscriptions.userId], references: [users.id] }),
}));

export const questPostponementsRelations = relations(questPostponements, ({ one }) => ({
  user: one(users, { fields: [questPostponements.userId], references: [users.id] }),
  task: one(tasks, { fields: [questPostponements.taskId], references: [tasks.id] }),
}));

export const notificationChannelsRelations = relations(notificationChannels, ({ one }) => ({
  user: one(users, { fields: [notificationChannels.userId], references: [users.id] }),
}));

export const notificationLogRelations = relations(notificationLog, ({ one }) => ({
  user: one(users, { fields: [notificationLog.userId], references: [users.id] }),
}));

export const totpBackupCodesRelations = relations(totpBackupCodes, ({ one }) => ({
  user: one(users, { fields: [totpBackupCodes.userId], references: [users.id] }),
}));

export const authenticatorsRelations = relations(authenticators, ({ one }) => ({
  user: one(users, { fields: [authenticators.userId], references: [users.id] }),
}));
