/**
 * Drizzle ORM schema for the Momo application.
 * All tables are defined here and used for migration generation via drizzle-kit.
 *
 * Table overview:
 *  - users              Core user table, populated on first OAuth login
 *  - topics             User-defined project buckets to group tasks
 *  - tasks              All tasks (one-time, recurring, daily-eligible)
 *  - task_completions   Log of every task completion event
 *  - wishlist_items     Items a user wants to buy, with optional coin gating
 *  - achievements       Master list of available achievements (seeded)
 *  - user_achievements  Junction: which achievements a user has earned
 *  - api_keys           Personal Access Tokens for programmatic API access
 *  - linking_requests   Short-lived tokens for OAuth account linking flow
 *  - quest_postponements  Log of daily quest postponement events (for weekly review)
 */

import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  date,
  time,
  decimal,
  jsonb,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Enums ────────────────────────────────────────────────────────────────────

/** User interface theme preference */
export const themeEnum = pgEnum("theme", ["light", "dark", "system"]);

/** Task/topic priority levels */
export const priorityEnum = pgEnum("priority", ["HIGH", "NORMAL", "SOMEDAY"]);

/** Task type — controls recurrence and daily-quest eligibility */
export const taskTypeEnum = pgEnum("task_type", [
  "ONE_TIME",
  "RECURRING",
  "DAILY_ELIGIBLE",
]);

/** Task/user energy level — how much effort a task requires or the user has today */
export const energyLevelEnum = pgEnum("energy_level", ["HIGH", "MEDIUM", "LOW"]);

/** Wishlist item priority */
export const wishlistPriorityEnum = pgEnum("wishlist_priority", [
  "WANT",
  "NICE_TO_HAVE",
  "SOMEDAY",
]);

/** Wishlist item status */
export const wishlistStatusEnum = pgEnum("wishlist_status", [
  "OPEN",
  "BOUGHT",
  "DISCARDED",
]);

// ─── Tables ───────────────────────────────────────────────────────────────────

/**
 * Core user table.
 * Populated/updated on first OAuth login via Auth.js Drizzle adapter.
 * Extended with Momo-specific gamification and preference fields.
 *
 * The columns `name`, `email`, `emailVerified`, and `image` are required by
 * the Auth.js Drizzle adapter. Custom Momo fields are added alongside them.
 */
export const users = pgTable("users", {
  /** Primary key — UUID generated by the DB */
  id: uuid("id").primaryKey().defaultRandom(),

  /** Display name from the OAuth provider (required by Auth.js adapter) */
  name: text("name"),

  /** Email from the OAuth provider (required by Auth.js adapter) */
  email: text("email").unique(),

  /** Timestamp of email verification (required by Auth.js adapter) */
  emailVerified: timestamp("email_verified", { mode: "date" }),

  /** Avatar URL from the OAuth provider (required by Auth.js adapter) */
  image: text("image"),

  /** Composite identifier from the OAuth provider (e.g. "github:12345678") */
  providerId: text("provider_id").unique(),

  /** Gamification coin balance */
  coins: integer("coins").notNull().default(0),

  /** Gamification level */
  level: integer("level").notNull().default(1),

  /** Current streak length in days */
  streakCurrent: integer("streak_current").notNull().default(0),

  /** All-time maximum streak length */
  streakMax: integer("streak_max").notNull().default(0),

  /** Date of the last streak-qualifying action */
  streakLastDate: date("streak_last_date"),

  /** Monthly budget for wishlist tracking (decimal for currency precision) */
  monthlyBudget: decimal("monthly_budget", { precision: 10, scale: 2 }),

  /** Whether the user has enabled push notifications */
  notificationEnabled: boolean("notification_enabled").notNull().default(false),

  /** Time of day for the daily notification (24h format, in the user's local timezone) */
  notificationTime: time("notification_time").notNull().default("08:00"),

  /**
   * IANA timezone identifier (e.g. "Europe/Berlin", "America/New_York").
   * Used to interpret notificationTime in the user's local time rather than UTC.
   * NULL falls back to UTC.
   */
  timezone: text("timezone"),

  /** User's preferred colour theme */
  theme: themeEnum("theme").notNull().default("system"),

  /** How many times the user has postponed their daily quest today */
  questPostponesToday: integer("quest_postpones_today").notNull().default(0),

  /** Date on which questPostponesToday was last incremented — used for daily reset */
  questPostponedDate: date("quest_postponed_date"),

  /** Maximum number of daily quest postponements allowed per day (1–5, default 3) */
  questPostponeLimit: integer("quest_postpone_limit").notNull().default(3),

  /**
   * Cumulative count of tasks ever created by this user.
   * Incremented on createTask() and never decremented — gives a true "tasks created" stat
   * even after tasks are deleted.
   */
  totalTasksCreated: integer("total_tasks_created").notNull().default(0),

  /** Whether to show an affirmation/quote after completing the daily quest (default: on) */
  emotionalClosureEnabled: boolean("emotional_closure_enabled").notNull().default(true),

  /** Today's self-reported energy level for daily quest matching. Null = not yet checked in today. */
  energyLevel: energyLevelEnum("energy_level"),

  /** Date on which energyLevel was set (YYYY-MM-DD in user's timezone) — used for daily reset */
  energyLevelDate: date("energy_level_date"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Auth.js required tables for the Drizzle adapter.
 * These must match the exact column structure expected by @auth/drizzle-adapter.
 * See: https://authjs.dev/getting-started/adapters/drizzle
 */

/** OAuth account links — one user can have multiple OAuth accounts */
export const accounts = pgTable(
  "accounts",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (table) => ({
    compoundKey: unique().on(table.provider, table.providerAccountId),
  })
);

/** Active sessions — sessionToken is the primary key */
export const sessions = pgTable("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),
});

/** Magic link / email verification tokens */
export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (table) => ({
    compositeKey: unique().on(table.identifier, table.token),
  })
);

/**
 * Topics — user-defined project buckets to group tasks.
 * Examples: "Moving", "Tax Return", "Health", "Side Project"
 */
export const topics = pgTable("topics", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  title: text("title").notNull(),

  description: text("description"),

  /** Optional hex or CSS color for UI display */
  color: text("color"),

  /** Optional emoji or icon identifier */
  icon: text("icon"),

  /** Priority affects daily quest topic selection */
  priority: priorityEnum("priority").notNull().default("NORMAL"),

  /** Archived topics are hidden from the main view but not deleted */
  archived: boolean("archived").notNull().default(false),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Tasks — the core entity of Momo.
 * Supports one-time, recurring, and daily-quest-eligible types.
 */
export const tasks = pgTable("tasks", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** Optional topic association */
  topicId: uuid("topic_id").references(() => topics.id, {
    onDelete: "set null",
  }),

  title: text("title").notNull(),

  notes: text("notes"),

  /**
   * Task type:
   *  - ONE_TIME: completed once and done
   *  - RECURRING: repeats on a schedule (recurrence_interval days)
   *  - DAILY_ELIGIBLE: can be selected as the daily quest
   */
  type: taskTypeEnum("type").notNull(),

  priority: priorityEnum("priority").notNull().default("NORMAL"),

  /** For RECURRING tasks: number of days between occurrences */
  recurrenceInterval: integer("recurrence_interval"),

  /** Original due date (user-set) */
  dueDate: date("due_date"),

  /** Computed next due date for recurring tasks */
  nextDueDate: date("next_due_date"),

  /** Set when a ONE_TIME task is completed */
  completedAt: timestamp("completed_at"),

  /** Coin reward for completing this task */
  coinValue: integer("coin_value").notNull().default(1),

  /** Whether this task is currently selected as the daily quest */
  isDailyQuest: boolean("is_daily_quest").notNull().default(false),

  /** Date on which this task was last assigned as the daily quest (YYYY-MM-DD in user's timezone) */
  dailyQuestDate: date("daily_quest_date"),

  /** How many times this task has been postponed as a daily quest (across all days) */
  postponeCount: integer("postpone_count").notNull().default(0),

  /** Estimated time to complete this task in minutes (5 / 15 / 30 / 60 / null = unknown) */
  estimatedMinutes: integer("estimated_minutes"),

  /** Date until which this task is snoozed/hidden (YYYY-MM-DD). Null = active/visible. */
  snoozedUntil: date("snoozed_until"),

  /** Energy level required to complete this task. Null = matches any energy state. */
  energyLevel: energyLevelEnum("energy_level"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Task completions log.
 * Every completion event is recorded here — including recurring task completions.
 */
export const taskCompletions = pgTable("task_completions", {
  id: uuid("id").primaryKey().defaultRandom(),

  taskId: uuid("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  completedAt: timestamp("completed_at").notNull().defaultNow(),
});

/**
 * Wishlist items — things the user wants to buy.
 * Optionally gated behind a coin threshold for mindful spending.
 */
export const wishlistItems = pgTable("wishlist_items", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  title: text("title").notNull(),

  /** Price in the user's currency (stored as decimal for precision) */
  price: decimal("price", { precision: 10, scale: 2 }),

  /** Optional product/service URL */
  url: text("url"),

  priority: wishlistPriorityEnum("priority").notNull(),

  status: wishlistStatusEnum("status").notNull().default("OPEN"),

  /** Minimum coin balance required to mark as bought */
  coinUnlockThreshold: integer("coin_unlock_threshold"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Master achievements table.
 * Seeded with all available achievements; users earn them via user_achievements.
 */
export const achievements = pgTable("achievements", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** Unique machine-readable key (e.g. "first_task_completed") */
  key: text("key").notNull().unique(),

  title: text("title").notNull(),

  description: text("description").notNull(),

  /** Emoji or icon identifier for display */
  icon: text("icon").notNull(),
});

/**
 * Junction table tracking which achievements each user has earned.
 * The unique index on (user_id, achievement_id) prevents duplicate awards.
 */
export const userAchievements = pgTable(
  "user_achievements",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    achievementId: uuid("achievement_id")
      .notNull()
      .references(() => achievements.id, { onDelete: "cascade" }),

    earnedAt: timestamp("earned_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("user_achievements_user_id_achievement_id_unique").on(
      table.userId,
      table.achievementId
    ),
  ]
);

/**
 * Personal Access Tokens (API Keys) for programmatic access to the Momo API.
 *
 * Each key is stored as a SHA-256 hash of the plaintext token — the plaintext
 * is only ever shown once at creation time and never persisted.
 *
 * Key format (256-bit entropy): `momo_live_<44 chars base64url(32 random bytes)>`
 *
 * Fields:
 *  - keyHash    SHA-256(plaintext key) — used for O(1) lookup at auth time
 *  - keyPrefix  First 16 chars of the plaintext + "..." for display in the UI
 *  - readonly   If true, the key may only be used for GET requests
 *  - expiresAt  NULL = never expires; otherwise refused after this timestamp
 *  - revokedAt  NULL = active; set to revoke the key immediately
 *  - lastUsedAt Updated on each successful auth — useful for activity tracking
 */
export const apiKeys = pgTable("api_keys", {
  id: uuid("id").primaryKey().defaultRandom(),

  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** User-defined label (e.g. "Claude MCP", "Home automation") */
  name: text("name").notNull(),

  /** SHA-256 hash of the plaintext API key — indexed, O(1) lookup */
  keyHash: text("key_hash").notNull().unique(),

  /** Display prefix: first 16 chars of plaintext + "..." (never the full key) */
  keyPrefix: text("key_prefix").notNull(),

  /** If true, key may only be used for GET requests (read-only access) */
  readonly: boolean("readonly").notNull().default(false),

  /** NULL = never expires */
  expiresAt: timestamp("expires_at"),

  /** Timestamp of last successful authentication — NULL if never used */
  lastUsedAt: timestamp("last_used_at"),

  /** Set when the key is revoked — NULL means the key is still active */
  revokedAt: timestamp("revoked_at"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Short-lived tokens used during the OAuth account linking flow.
 *
 * When a logged-in user wants to connect an additional OAuth provider, Momo:
 *  1. Creates a linking_request record with the user's ID and target provider
 *  2. Redirects the user through the OAuth flow
 *  3. In the OAuth callback, reads this token to find the original user and
 *     merge the new OAuth account onto them
 *
 * Tokens expire after 5 minutes to limit the attack surface.
 */
export const linkingRequests = pgTable("linking_requests", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user who initiated the linking request */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** Target OAuth provider (e.g. "github", "discord", "google", "keycloak") */
  provider: text("provider").notNull(),

  /** Tokens expire after 5 minutes */
  expiresAt: timestamp("expires_at").notNull(),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * Cron run log — one row per cron job execution.
 * Used to track push-notification delivery history and detect stale/missing cron jobs.
 * Visible on the admin page and via /api/health (non-blocking).
 */
export const cronRuns = pgTable("cron_runs", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** Cron job name (e.g. "daily-quest") */
  name: text("name").notNull(),

  /** When the cron started */
  ranAt: timestamp("ran_at", { withTimezone: true }).notNull().defaultNow(),

  /** Number of push notifications successfully sent */
  sent: integer("sent").notNull().default(0),

  /** Number of push notifications that failed */
  failed: integer("failed").notNull().default(0),

  /** Execution time in milliseconds */
  durationMs: integer("duration_ms"),
});

/**
 * Per-device push subscriptions.
 *
 * One row per (user, browser/device) combination. The push endpoint URL is
 * globally unique — it identifies a specific browser push subscription.
 * This allows a user to receive notifications on multiple devices simultaneously.
 *
 * Lifecycle:
 *  - Created/updated when user enables notifications on a device (POST /api/push/subscribe)
 *  - Deleted when user disables notifications on that device (DELETE /api/push/subscribe)
 *  - Automatically deleted by sendPushNotification() when the push service returns 410 Gone
 */
export const pushSubscriptions = pgTable("push_subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user this subscription belongs to */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /**
   * The push endpoint URL — globally unique, identifies one browser/device.
   * Used as the upsert key: subscribing twice from the same device updates the row.
   */
  endpoint: text("endpoint").notNull().unique(),

  /** Full W3C PushSubscription JSON (endpoint + keys) */
  subscription: jsonb("subscription").notNull(),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Quest postponement log — one row per daily quest postponement.
 * Used to compute precise weekly postponement counts for the weekly review feature.
 * Historical data starts accumulating from the migration date forward.
 */
export const questPostponements = pgTable("quest_postponements", {
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user who postponed the quest */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /** The task that was postponed */
  taskId: uuid("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),

  /** When the postponement happened */
  postponedAt: timestamp("postponed_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Relations ────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  accounts: many(accounts),
  sessions: many(sessions),
  topics: many(topics),
  tasks: many(tasks),
  taskCompletions: many(taskCompletions),
  wishlistItems: many(wishlistItems),
  userAchievements: many(userAchievements),
  apiKeys: many(apiKeys),
  linkingRequests: many(linkingRequests),
  pushSubscriptions: many(pushSubscriptions),
  questPostponements: many(questPostponements),
}));

export const apiKeysRelations = relations(apiKeys, ({ one }) => ({
  user: one(users, { fields: [apiKeys.userId], references: [users.id] }),
}));

export const linkingRequestsRelations = relations(linkingRequests, ({ one }) => ({
  user: one(users, { fields: [linkingRequests.userId], references: [users.id] }),
}));

export const topicsRelations = relations(topics, ({ one, many }) => ({
  user: one(users, { fields: [topics.userId], references: [users.id] }),
  tasks: many(tasks),
}));

export const tasksRelations = relations(tasks, ({ one, many }) => ({
  user: one(users, { fields: [tasks.userId], references: [users.id] }),
  topic: one(topics, { fields: [tasks.topicId], references: [topics.id] }),
  completions: many(taskCompletions),
}));

export const taskCompletionsRelations = relations(
  taskCompletions,
  ({ one }) => ({
    task: one(tasks, {
      fields: [taskCompletions.taskId],
      references: [tasks.id],
    }),
    user: one(users, {
      fields: [taskCompletions.userId],
      references: [users.id],
    }),
  })
);

export const wishlistItemsRelations = relations(wishlistItems, ({ one }) => ({
  user: one(users, { fields: [wishlistItems.userId], references: [users.id] }),
}));

export const userAchievementsRelations = relations(
  userAchievements,
  ({ one }) => ({
    user: one(users, {
      fields: [userAchievements.userId],
      references: [users.id],
    }),
    achievement: one(achievements, {
      fields: [userAchievements.achievementId],
      references: [achievements.id],
    }),
  })
);

export const pushSubscriptionsRelations = relations(pushSubscriptions, ({ one }) => ({
  user: one(users, { fields: [pushSubscriptions.userId], references: [users.id] }),
}));

export const questPostponementsRelations = relations(questPostponements, ({ one }) => ({
  user: one(users, { fields: [questPostponements.userId], references: [users.id] }),
  task: one(tasks, { fields: [questPostponements.taskId], references: [tasks.id] }),
}));
