import { createRequire } from "node:module";
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// eslint-config-next ships `settings.react.version = "detect"`, which makes
// eslint-plugin-react probe the filesystem per linted file via
// `context.getFilename()`. ESLint 10 removed that method (it is `context.filename`
// now), and eslint-plugin-react 7.37.5 — its newest release — still calls the old
// one, so "detect" crashes the whole run:
//
//   TypeError: Error while loading rule 'react/display-name':
//   contextOrFilename.getFilename is not a function
//
// Reading the version here does what "detect" was for, without the removed API:
// the same number, resolved once at config load instead of per file.
const reactVersion = createRequire(import.meta.url)("react/package.json").version;

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated PWA service worker files (produced by @ducanh2912/next-pwa at build time)
    "public/sw.js",
    "public/workbox-*.js",
    "public/worker-*.js",
    // Build artifacts of the standalone Alexa Lambda subproject
    "alexa-skill/dist/**",
    // Coverage reports generated by @vitest/coverage-v8
    "coverage/**",
  ]),
  {
    settings: {
      react: { version: reactVersion },
    },
  },
  {
    // eslint-plugin-react-hooks 7.1 tightened `set-state-in-effect` from an
    // opt-in lint to an error, which turns ten previously-green components red
    // in a dependency bump that touches no application code. The findings are
    // real — each site calls setState synchronously inside an effect, which
    // costs an extra render pass — but fixing them means reshaping ten
    // components' state flow, and that is not work that belongs in a
    // dependency PR where it cannot be reviewed on its own merits.
    //
    // Downgraded to a warning rather than pinned back to 7.0.1: keeping the
    // plugin current is the point of lockfile maintenance, and a warning stays
    // visible in every lint run where a pin would have gone quiet. Tracked in
    // ROADMAP.md under "set-state-in-effect".
    rules: {
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);

export default eslintConfig;
